//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCdiario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos
    {
        public int id_articulos { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public int id_ubicacion { get; set; }
        public string id_usuario { get; set; }
    
        public virtual ubicaciones ubicaciones { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
