//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCdiario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.articulos = new HashSet<articulos>();
            this.noticias = new HashSet<noticias>();
        }
    
        public string correo { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string contrasena { get; set; }
    
        public virtual ICollection<articulos> articulos { get; set; }
        public virtual ICollection<noticias> noticias { get; set; }
    }
}
